GET http://localhost:3003/user
Content-Type: application/json

###

GET http://localhost:3003/users/types?type=ADMIN
Content-Type: application/json

###

GET http://localhost:3003/users/name?name=Alice
Content-Type: application/json

###

GET http://localhost:3003/users
Content-Type: application/json

###
POST http://localhost:3003/users?name=Roberta
Content-Type: application/json