POST http://localhost:3003/user/signup
Content-Type: application/json

{
 
   "email": "robsonmarques@gmail.com",
   "password": "123987" 

}
### 
POST http://localhost:3003/user/login
Content-Type: application/json

{
   "email": "gustavoloreale@gmail.com",
   "password": "456321"  
}
###

GET http://localhost:3003/user/profile
Authorization:


